org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.73

mod_id=another_config_manager
mod_name=Another Config Manager
mod_license=MIT
mod_version=1.0.0.0.0
mod_group_id=net.unfamily.anotherconfigmanager
mod_authors=Unfamily, Iskandert
mod_description=Config browser and editor for NeoForge ModConfigSpec trees, with CSV and color managers.
